package middleware

import (
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// HTTP 请求指标
	httpRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_requests_total",
			Help: "Total number of HTTP requests",
		},
		[]string{"method", "path", "status"},
	)

	httpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_duration_seconds",
			Help:    "HTTP request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "path"},
	)

	httpRequestsInFlight = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "http_requests_in_flight",
			Help: "Current number of in-flight HTTP requests",
		},
	)

	// 业务指标
	xrfMeasurementsReceived = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "xrf_measurements_received_total",
			Help: "Total number of XRF measurements received",
		},
	)

	xrfMeasurementsFailed = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "xrf_measurements_failed_total",
			Help: "Total number of failed XRF measurements",
		},
	)

	alertsGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "alerts_generated_total",
			Help: "Total number of alerts generated by severity",
		},
		[]string{"severity"},
	)

	alertsEmailsSent = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "alerts_emails_sent_total",
			Help: "Total number of alert emails sent",
		},
	)

	fingerprintMatches = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "fingerprint_matches_total",
			Help: "Total number of fingerprint matching operations",
		},
	)

	remediationAssessments = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "remediation_assessments_total",
			Help: "Total number of remediation assessments",
		},
	)

	pcaComputations = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "pca_computations_total",
			Help: "Total number of PCA computations",
		},
	)

	// 数据库查询指标
	dbQueryDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "db_query_duration_seconds",
			Help:    "Database query duration in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
		},
		[]string{"operation"},
	)

	// EventBus 指标
	eventBusPublished = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "eventbus_published_total",
			Help: "Total number of events published on the EventBus",
		},
		[]string{"event_type"},
	)

	eventBusDropped = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "eventbus_dropped_total",
			Help: "Total number of events dropped due to full channel",
		},
		[]string{"event_type"},
	)
)

// PrometheusMetrics Gin 中间件：收集 HTTP 请求指标
func PrometheusMetrics() gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()
		httpRequestsInFlight.Inc()

		c.Next()

		httpRequestsInFlight.Dec()
		duration := time.Since(start).Seconds()

		status := strconv.Itoa(c.Writer.Status())
		path := c.FullPath()
		if path == "" {
			path = "unknown"
		}

		httpRequestsTotal.WithLabelValues(c.Request.Method, path, status).Inc()
		httpRequestDuration.WithLabelValues(c.Request.Method, path).Observe(duration)
	}
}

// 业务指标导出函数（供各模块调用）
func IncXRFReceived()          { xrfMeasurementsReceived.Inc() }
func IncXRFFailed()            { xrfMeasurementsFailed.Inc() }
func IncAlert(severity string) { alertsGenerated.WithLabelValues(severity).Inc() }
func IncEmailSent()            { alertsEmailsSent.Inc() }
func IncFingerprintMatch()     { fingerprintMatches.Inc() }
func IncRemediationAssessment(){ remediationAssessments.Inc() }
func IncPCAComputation()       { pcaComputations.Inc() }

func ObserveDBQuery(op string, d time.Duration) {
	dbQueryDuration.WithLabelValues(op).Observe(d.Seconds())
}

func IncEventPublished(t string) { eventBusPublished.WithLabelValues(t).Inc() }
func IncEventDropped(t string)   { eventBusDropped.WithLabelValues(t).Inc() }
